# Generated by Django 5.1.3 on 2025-08-27 19:34

import aplication.core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_fecha_hora_de_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, validators=[aplication.core.utils.valida_cedula]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Caracteres inválidos para un número de teléfono.', regex='^\\d{9,15}$')]),
        ),
    ]
