# Generated by Django 5.2.5 on 2025-09-01 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_cedula_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='fecha_devolucion',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='codigo_equipo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientodetalle',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Caracteres inválidos para un número de teléfono.', regex='^\\d{9,11}$')]),
        ),
    ]
