# Generated by Django 5.1.3 on 2025-09-04 19:05

import aplication.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[aplication.core.utils.valida_cedula]),
        ),
    ]
